//! Adapters that present the I2C WHO_AM_I slave (generated by Verilator) as an [`I2cPinModel`].
//!
//! - [`VerilatedWhoAmI`]: `i2c_whoami.v` as is. The smallest form of an adapter: the RTL has no system
//!   clock and runs on SCL / SDA only, so it is evaluated whenever a line changes, and returns no
//!   `period_ps`
//! - [`VerilatedWhoAmITop`]: the same slave as a chip top (`i2c_whoami_top.v`): SDA is an `inout` pad
//!   without output enable, and there is no reset pin but a power-on reset from `vdd`. Verilator cannot
//!   take `inout` at the top, so a simulation-only wrapper (`sim/i2c_whoami_sim.v`) resolves SDA

use crate::bindings::{i2c_whoami, i2c_whoami_sim};
use virtual_bus::bus::i2c::sim::I2cPinModel;

/// I2C WHO_AM_I slave (address 0x29, 0x0F = 0xA5, 0x10 = SCRATCH)
pub struct VerilatedWhoAmI {
    m: i2c_whoami::Model,
}

impl VerilatedWhoAmI {
    pub const ADDRESS: u8 = 0x29;
    pub const WHO_AM_I: u8 = 0xA5;

    /// Creates the model and resets it.
    ///
    /// Verilator initializes ports to 0, so `rst_n` is set to 1 and then to 0
    /// to create the falling edge of the asynchronous reset (1 → 0 → 1)
    pub fn new() -> Self {
        let mut m = i2c_whoami::Model::new();
        m.set_scl(true);
        m.set_sda_i(true);
        for level in [true, false, true] {
            m.set_rst_n(level);
            m.eval();
        }
        Self { m }
    }
}

impl Default for VerilatedWhoAmI {
    fn default() -> Self {
        Self::new()
    }
}

impl I2cPinModel for VerilatedWhoAmI {
    fn set_inputs(&mut self, scl: bool, sda: bool) {
        self.m.set_scl(scl);
        self.m.set_sda_i(sda);
        self.m.eval();
    }

    fn sda_low(&self) -> bool {
        self.m.sda_low()
    }
}

/// The WHO_AM_I slave as a chip top: `inout` SDA without output enable, power-on reset from `vdd`.
///
/// The wrapper resolves SDA (pull-up and wired-AND) inside, so the Rust side sees only the resolved
/// level `sda_level`. Whether the chip itself pulls SDA is derived from "low although nobody outside
/// pulls it". For that the bus must hand over the SDA level driven by everyone else, which is what
/// [`I2cPinModel::wants_external_sda`] asks for: fed the resolved level including its own pull, the
/// chip could never let go of the line.
///
/// While the power ([`Self::set_vdd`]) is off, the chip is held in reset and does not ACK its address;
/// the registers return to their reset values the moment power comes back
pub struct VerilatedWhoAmITop {
    m: i2c_whoami_sim::Model,
    /// Whether someone other than the chip pulls SDA low
    ext_low: bool,
}

impl VerilatedWhoAmITop {
    pub const ADDRESS: u8 = VerilatedWhoAmI::ADDRESS;
    pub const WHO_AM_I: u8 = VerilatedWhoAmI::WHO_AM_I;

    /// Creates the model with power on
    pub fn new() -> Self {
        let mut s = Self::new_unpowered();
        s.set_vdd(true);
        s
    }

    /// Creates the model with power off
    pub fn new_unpowered() -> Self {
        let mut m = i2c_whoami_sim::Model::new();
        m.set_scl(true);
        m.set_ext_sda_low(false);
        // vdd 1 → 0, so that the reset surely happens (staying at the initial 0 gives no edge)
        for level in [true, false] {
            m.set_vdd(level);
            m.eval();
        }
        Self { m, ext_low: false }
    }

    /// Turns the power (vdd) on or off. gnd is tied to 0 inside the wrapper
    pub fn set_vdd(&mut self, on: bool) {
        self.m.set_vdd(on);
        self.m.eval();
    }

    /// The SDA level resolved inside the wrapper
    pub fn sda_level(&self) -> bool {
        self.m.sda_level()
    }
}

impl Default for VerilatedWhoAmITop {
    fn default() -> Self {
        Self::new()
    }
}

impl I2cPinModel for VerilatedWhoAmITop {
    fn set_inputs(&mut self, scl: bool, external_sda: bool) {
        self.ext_low = !external_sda;
        self.m.set_scl(scl);
        self.m.set_ext_sda_low(self.ext_low);
        self.m.eval();
    }

    fn sda_low(&self) -> bool {
        !self.sda_level() && !self.ext_low
    }

    fn wants_external_sda(&self) -> bool {
        true
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use embedded_hal::i2c::{ErrorKind, I2c, NoAcknowledgeSource};
    use virtual_bus::bus::i2c::sim::{LineEvent, PinLevelI2cSlave, SimI2cBus};
    use virtual_bus::devices::register::{I2cFormat, RegisterMap};
    use virtual_bus::{VirtualI2cBus, shared};

    /// A Rust model to put on the same bus as the RTL (0x00..=0x01 are read-write registers)
    fn rust_regs() -> RegisterMap {
        RegisterMap::new().rw(0x00, 0).rw(0x01, 0)
    }

    // the scenarios below run on the core and on the chip top

    fn reads_who_am_i(dut: impl I2cPinModel + 'static) {
        let bus = SimI2cBus::new();
        bus.attach(dut);
        let mut i2c = bus.master(400_000);
        let mut b = [0u8; 2];
        i2c.write_read(0x29, &[0x0F], &mut b).unwrap();
        assert_eq!(b, [0xA5, 0x00]);
    }

    fn scratch_round_trip_and_wrong_address(dut: impl I2cPinModel + 'static) {
        let bus = SimI2cBus::new();
        bus.attach(dut);
        let mut i2c = bus.master(100_000);
        i2c.write(0x29, &[0x10, 0x3C]).unwrap();
        let mut b = [0u8];
        i2c.write_read(0x29, &[0x10], &mut b).unwrap();
        assert_eq!(b[0], 0x3C);
        assert_eq!(
            i2c.write(0x2A, &[0]),
            Err(ErrorKind::NoAcknowledge(NoAcknowledgeSource::Address))
        );
        // the bus is released after the failure
        assert!(bus.scl() && bus.sda());
    }

    /// The RTL and a Rust model on the same signal lines
    fn shares_wires_with_rust_pin_model(dut: impl I2cPinModel + 'static) {
        let m = rust_regs();
        let bus = SimI2cBus::new();
        bus.attach(dut);
        bus.attach(PinLevelI2cSlave::new(0x20, m.i2c(I2cFormat::new())));
        let mut i2c = bus.master(400_000);
        i2c.write(0x20, &[0x00, 0x81, 0x7E]).unwrap();
        let mut b = [0u8];
        i2c.write_read(0x29, &[0x0F], &mut b).unwrap();
        assert_eq!(b[0], 0xA5);
        let mut b = [0u8; 2];
        i2c.write_read(0x20, &[0x00], &mut b).unwrap();
        assert_eq!(b, [0x81, 0x7E]);
        assert_eq!(m.get(0x01), 0x7E);
    }

    #[test]
    fn core_reads_who_am_i() {
        reads_who_am_i(VerilatedWhoAmI::new());
    }

    #[test]
    fn top_reads_who_am_i() {
        reads_who_am_i(VerilatedWhoAmITop::new());
    }

    #[test]
    fn core_scratch_round_trip_and_wrong_address() {
        scratch_round_trip_and_wrong_address(VerilatedWhoAmI::new());
    }

    #[test]
    fn top_scratch_round_trip_and_wrong_address() {
        scratch_round_trip_and_wrong_address(VerilatedWhoAmITop::new());
    }

    #[test]
    fn core_shares_wires_with_rust_pin_model() {
        shares_wires_with_rust_pin_model(VerilatedWhoAmI::new());
    }

    #[test]
    fn top_shares_wires_with_rust_pin_model() {
        shares_wires_with_rust_pin_model(VerilatedWhoAmITop::new());
    }

    /// The RTL at pin level and a Rust model at transaction level behind one `VirtualI2cBus`
    #[test]
    fn mixed_virtual_bus() {
        let lines = SimI2cBus::new();
        lines.attach(VerilatedWhoAmI::new());
        let m = rust_regs();
        let mut bus = VirtualI2cBus::new();
        bus.attach(0x20, m.i2c(I2cFormat::new())).unwrap();
        bus.attach_i2c(0x29, lines.master(400_000)).unwrap();

        let mut who = [0u8];
        bus.write_read(0x29, &[0x0F], &mut who).unwrap();
        bus.write(0x20, &[0x01, who[0]]).unwrap();
        assert_eq!(m.get(0x01), 0xA5);
        // accessing the Rust model does not advance the time of the signal lines
        let t = lines.now_ns();
        bus.write(0x20, &[0x01, 0]).unwrap();
        assert_eq!(lines.now_ns(), t);
    }

    /// The line changes for the same sequence of operations
    fn trace_of(dut: impl I2cPinModel + 'static) -> Vec<LineEvent> {
        let bus = SimI2cBus::new();
        bus.attach(dut);
        let mut i2c = bus.master(400_000);
        bus.enable_trace();
        i2c.write(0x29, &[0x10, 0x96]).unwrap();
        let mut b = [0u8; 2];
        i2c.write_read(0x29, &[0x0F], &mut b).unwrap();
        bus.trace()
    }

    #[test]
    fn core_and_top_produce_the_same_waveform() {
        // the same circuit inside, so the inout pad and the wrapper do not change the lines by even 1 ps
        assert_eq!(
            trace_of(VerilatedWhoAmI::new()),
            trace_of(VerilatedWhoAmITop::new())
        );
    }

    // ---- power-on reset (chip top) ----

    #[test]
    fn top_does_not_ack_while_unpowered() {
        let dut = shared(VerilatedWhoAmITop::new_unpowered());
        let bus = SimI2cBus::new();
        bus.attach(dut.clone());
        let mut i2c = bus.master(400_000);
        let nack = Err(ErrorKind::NoAcknowledge(NoAcknowledgeSource::Address));

        // no response without power
        assert_eq!(i2c.write(0x29, &[0x0F]), nack);

        // responds once powered
        dut.borrow_mut().set_vdd(true);
        let mut b = [0u8];
        i2c.write_read(0x29, &[0x0F], &mut b).unwrap();
        assert_eq!(b[0], 0xA5);
    }

    #[test]
    fn top_power_cycle_resets_registers() {
        let dut = shared(VerilatedWhoAmITop::new());
        let bus = SimI2cBus::new();
        bus.attach(dut.clone());
        let mut i2c = bus.master(400_000);
        i2c.write(0x29, &[0x10, 0x5C]).unwrap();
        let mut b = [0u8];
        i2c.write_read(0x29, &[0x10], &mut b).unwrap();
        assert_eq!(b[0], 0x5C);

        // power cycle
        dut.borrow_mut().set_vdd(false);
        bus.run_ns(1_000);
        dut.borrow_mut().set_vdd(true);
        bus.run_ns(1_000);

        i2c.write_read(0x29, &[0x10], &mut b).unwrap();
        assert_eq!(b[0], 0x00, "SCRATCH did not return to its reset value");
        i2c.write_read(0x29, &[0x0F], &mut b).unwrap();
        assert_eq!(b[0], 0xA5);
    }
}
