//! Adapters that present the RTL of the I2C WHO_AM_I slave (generated by Verilator) as an [`I2cPinModel`].
//!
//! - [`VerilatedWhoAmI`]: uses the `i2c_whoami.v` core (separate `sda_i` / `sda_low` ports) as is.
//!   Oversamples SCL / SDA with a system clock
//! - [`VerilatedWhoAmITop`]: the chip top without output enable (`i2c_whoami_top.v`, SDA is inout),
//!   wrapped in a simulation wrapper (`sim/i2c_whoami_sim.v`)
//! - [`VerilatedWhoAmIScl`]: `i2c_whoami_scl.v`. No system clock; runs on SCL / SDA only

use std::io;
use std::path::Path;

use crate::bindings::{i2c_whoami, i2c_whoami_scl, i2c_whoami_sim};
use virtual_bus::bus::i2c::sim::I2cPinModel;

/// I2C WHO_AM_I slave (address 0x29, 0x0F = 0xA5, 0x10 = SCRATCH).
/// 50 MHz system clock
pub struct VerilatedWhoAmI {
    m: i2c_whoami::Model,
}

impl VerilatedWhoAmI {
    pub const ADDRESS: u8 = 0x29;
    pub const WHO_AM_I: u8 = 0xA5;
    pub const PERIOD_PS: u64 = 20_000;

    /// Creates the model and resets it.
    ///
    /// The RTL reset is asynchronous, so no clock is needed. Verilator initializes ports to 0, though,
    /// so `rst_n` is set to 1 and then to 0 to create a falling edge
    pub fn new() -> Self {
        Self::reset(i2c_whoami::Model::new())
    }

    /// Like [`Self::new`], and writes a VCD of every signal in the RTL to `path`,
    /// at the bus's simulated time. The VCD is closed when the model is dropped
    pub fn with_vcd(path: impl AsRef<Path>) -> io::Result<Self> {
        let mut m = i2c_whoami::Model::new();
        m.open_vcd(path)?;
        Ok(Self::reset(m))
    }

    fn reset(mut m: i2c_whoami::Model) -> Self {
        m.set_scl(true);
        m.set_sda_i(true);
        for level in [true, false, true] {
            m.set_rst_n(level);
            m.eval();
        }
        Self { m }
    }

    fn clock(&mut self) {
        self.m.set_clk(false);
        // in the VCD, the low half goes half a period before this rising edge
        self.m.eval_before(Self::PERIOD_PS / 2);
        self.m.set_clk(true);
        self.m.eval();
    }
}

impl Default for VerilatedWhoAmI {
    fn default() -> Self {
        Self::new()
    }
}

impl I2cPinModel for VerilatedWhoAmI {
    fn set_inputs(&mut self, scl: bool, sda: bool) {
        // a synchronous circuit: evaluating on the system clock is enough.
        // When writing a VCD, evaluate now too so the inputs show up when they change
        self.m.set_scl(scl);
        self.m.set_sda_i(sda);
        if self.m.is_tracing() {
            self.m.eval();
        }
    }

    fn period_ps(&self) -> Option<u64> {
        Some(Self::PERIOD_PS)
    }

    fn tick(&mut self) {
        self.clock();
    }

    fn sda_low(&self) -> bool {
        self.m.sda_low()
    }

    fn set_time_ps(&mut self, now_ps: u64) {
        self.m.set_time_ps(now_ps);
    }
}

/// WHO_AM_I slave as a chip top without output enable.
///
/// SDA is resolved (pull-up and wired-AND) inside the Verilog wrapper; the Rust side only sees
/// the resolved level `sda_level`. Whether the DUT itself is pulling SDA is derived from
/// "low although nobody outside pulls it". The wrapper is re-evaluated whenever an input changes,
/// so the derived value is always correct.
///
/// There is no reset pin; the Verilog creates a power-on reset from vdd.
/// While the power ([`Self::set_vdd`]) is off the chip is held in reset and does not ACK its address;
/// the registers return to their reset values the moment power comes back
pub struct VerilatedWhoAmITop {
    m: i2c_whoami_sim::Model,
    ext_low: bool,
}

impl VerilatedWhoAmITop {
    pub const ADDRESS: u8 = VerilatedWhoAmI::ADDRESS;
    pub const WHO_AM_I: u8 = VerilatedWhoAmI::WHO_AM_I;

    /// Creates the model with power on
    pub fn new() -> Self {
        let mut s = Self::new_unpowered();
        s.set_vdd(true);
        s
    }

    /// Creates the model with power off
    pub fn new_unpowered() -> Self {
        let mut m = i2c_whoami_sim::Model::new();
        m.set_scl(true);
        m.set_ext_sda_low(false);
        // move vdd 1 → 0 so the power-off reset surely happens (staying at the initial 0 gives no edge)
        for level in [true, false] {
            m.set_vdd(level);
            m.eval();
        }
        Self { m, ext_low: false }
    }

    /// Turns the power (vdd) on / off. gnd is tied to 0 inside the wrapper
    pub fn set_vdd(&mut self, on: bool) {
        self.m.set_vdd(on);
        self.m.eval();
    }

    fn clock(&mut self) {
        self.m.set_clk(false);
        self.m.eval();
        self.m.set_clk(true);
        self.m.eval();
    }

    /// The SDA level resolved inside the wrapper
    pub fn sda_level(&self) -> bool {
        self.m.sda_level()
    }
}

impl Default for VerilatedWhoAmITop {
    fn default() -> Self {
        Self::new()
    }
}

impl I2cPinModel for VerilatedWhoAmITop {
    fn set_inputs(&mut self, scl: bool, external_sda: bool) {
        self.ext_low = !external_sda;
        self.m.set_scl(scl);
        self.m.set_ext_sda_low(self.ext_low);
        // resolve the lines inside the wrapper (combinational logic) for the current levels.
        // This is not a clock edge, so the DUT's state does not change
        self.m.eval();
    }

    fn period_ps(&self) -> Option<u64> {
        Some(VerilatedWhoAmI::PERIOD_PS)
    }

    fn tick(&mut self) {
        self.clock();
    }

    fn sda_low(&self) -> bool {
        !self.sda_level() && !self.ext_low
    }

    fn wants_external_sda(&self) -> bool {
        true
    }
}

/// WHO_AM_I slave without a system clock, running on SCL / SDA only (`i2c_whoami_scl.v`).
///
/// Registers and behavior are the same as [`VerilatedWhoAmI`]. It is evaluated whenever a line changes,
/// so it returns no `period_ps`
pub struct VerilatedWhoAmIScl {
    m: i2c_whoami_scl::Model,
}

impl VerilatedWhoAmIScl {
    pub const ADDRESS: u8 = VerilatedWhoAmI::ADDRESS;
    pub const WHO_AM_I: u8 = VerilatedWhoAmI::WHO_AM_I;

    /// Creates the model and resets it (`rst_n` 1 → 0 → 1)
    pub fn new() -> Self {
        let mut m = i2c_whoami_scl::Model::new();
        m.set_scl(true);
        m.set_sda_i(true);
        for level in [true, false, true] {
            m.set_rst_n(level);
            m.eval();
        }
        Self { m }
    }
}

impl Default for VerilatedWhoAmIScl {
    fn default() -> Self {
        Self::new()
    }
}

impl I2cPinModel for VerilatedWhoAmIScl {
    fn set_inputs(&mut self, scl: bool, sda: bool) {
        self.m.set_scl(scl);
        self.m.set_sda_i(sda);
        self.m.eval();
    }

    fn sda_low(&self) -> bool {
        self.m.sda_low()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use embedded_hal::i2c::{ErrorKind, I2c, NoAcknowledgeSource};
    use virtual_bus::bus::i2c::sim::{LineEvent, PinLevelI2cSlave, SimI2cBus};
    use virtual_bus::devices::register::{I2cFormat, RegisterMap};
    use virtual_bus::{VirtualI2cBus, shared};

    /// A Rust model to put on the same bus as the RTL (0x00..=0x01 are read-write registers)
    fn rust_regs() -> RegisterMap {
        RegisterMap::new().rw(0x00, 0).rw(0x01, 0)
    }

    // the scenarios below run on the core (with output enable) and on the chip top (without)

    fn reads_who_am_i(dut: impl I2cPinModel + 'static) {
        let bus = SimI2cBus::new();
        bus.attach(dut);
        let mut i2c = bus.master(400_000);
        let mut b = [0u8; 2];
        i2c.write_read(0x29, &[0x0F], &mut b).unwrap();
        assert_eq!(b, [0xA5, 0x00]);
    }

    fn scratch_round_trip_and_wrong_address(dut: impl I2cPinModel + 'static) {
        let bus = SimI2cBus::new();
        bus.attach(dut);
        let mut i2c = bus.master(100_000);
        i2c.write(0x29, &[0x10, 0x3C]).unwrap();
        let mut b = [0u8];
        i2c.write_read(0x29, &[0x10], &mut b).unwrap();
        assert_eq!(b[0], 0x3C);
        assert_eq!(
            i2c.write(0x2A, &[0]),
            Err(ErrorKind::NoAcknowledge(NoAcknowledgeSource::Address))
        );
        // the bus is released after the failure
        assert!(bus.scl() && bus.sda());
    }

    fn shares_wires_with_rust_pin_model(dut: impl I2cPinModel + 'static) {
        let m = rust_regs();
        let bus = SimI2cBus::new();
        bus.attach(dut);
        bus.attach(PinLevelI2cSlave::new(0x20, m.i2c(I2cFormat::new())));
        let mut i2c = bus.master(400_000);
        i2c.write(0x20, &[0x00, 0x81, 0x7E]).unwrap();
        let mut b = [0u8];
        i2c.write_read(0x29, &[0x0F], &mut b).unwrap();
        assert_eq!(b[0], 0xA5);
        let mut b = [0u8; 2];
        i2c.write_read(0x20, &[0x00], &mut b).unwrap();
        assert_eq!(b, [0x81, 0x7E]);
        assert_eq!(m.get(0x01), 0x7E);
    }

    fn mixed_virtual_bus(dut: impl I2cPinModel + 'static) {
        let lines = SimI2cBus::new();
        lines.attach(dut);
        let m = rust_regs();
        let mut bus = VirtualI2cBus::new();
        bus.attach(0x20, m.i2c(I2cFormat::new())).unwrap();
        bus.attach_i2c(0x29, lines.master(400_000)).unwrap();

        let mut who = [0u8];
        bus.write_read(0x29, &[0x0F], &mut who).unwrap();
        bus.write(0x20, &[0x01, who[0]]).unwrap();
        assert_eq!(m.get(0x01), 0xA5);
        // accessing the Rust model does not advance the time of the signal lines
        let t = lines.now_ns();
        bus.write(0x20, &[0x01, 0]).unwrap();
        assert_eq!(lines.now_ns(), t);
    }

    #[test]
    fn core_reads_who_am_i() {
        reads_who_am_i(VerilatedWhoAmI::new());
    }

    #[test]
    fn top_reads_who_am_i() {
        reads_who_am_i(VerilatedWhoAmITop::new());
    }

    #[test]
    fn core_scratch_round_trip_and_wrong_address() {
        scratch_round_trip_and_wrong_address(VerilatedWhoAmI::new());
    }

    #[test]
    fn top_scratch_round_trip_and_wrong_address() {
        scratch_round_trip_and_wrong_address(VerilatedWhoAmITop::new());
    }

    #[test]
    fn core_shares_wires_with_rust_pin_model() {
        shares_wires_with_rust_pin_model(VerilatedWhoAmI::new());
    }

    #[test]
    fn top_shares_wires_with_rust_pin_model() {
        shares_wires_with_rust_pin_model(VerilatedWhoAmITop::new());
    }

    #[test]
    fn core_mixed_virtual_bus() {
        mixed_virtual_bus(VerilatedWhoAmI::new());
    }

    #[test]
    fn top_mixed_virtual_bus() {
        mixed_virtual_bus(VerilatedWhoAmITop::new());
    }

    #[test]
    fn scl_only_reads_who_am_i() {
        reads_who_am_i(VerilatedWhoAmIScl::new());
    }

    #[test]
    fn scl_only_scratch_round_trip_and_wrong_address() {
        scratch_round_trip_and_wrong_address(VerilatedWhoAmIScl::new());
    }

    #[test]
    fn scl_only_shares_wires_with_rust_pin_model() {
        shares_wires_with_rust_pin_model(VerilatedWhoAmIScl::new());
    }

    #[test]
    fn scl_only_mixed_virtual_bus() {
        mixed_virtual_bus(VerilatedWhoAmIScl::new());
    }

    /// The line changes for the same sequence of operations
    fn trace_of(dut: impl I2cPinModel + 'static) -> Vec<LineEvent> {
        let bus = SimI2cBus::new();
        bus.attach(dut);
        let mut i2c = bus.master(400_000);
        bus.enable_trace();
        i2c.write(0x29, &[0x10, 0x96]).unwrap();
        let mut b = [0u8; 2];
        i2c.write_read(0x29, &[0x0F], &mut b).unwrap();
        bus.trace()
    }

    #[test]
    fn core_and_top_produce_the_same_waveform() {
        // the same circuit inside, so wrapping it without output enable does not change the lines by even 1 ps
        assert_eq!(
            trace_of(VerilatedWhoAmI::new()),
            trace_of(VerilatedWhoAmITop::new())
        );
    }

    // ---- power-on reset (chip top) ----

    #[test]
    fn top_does_not_ack_while_unpowered() {
        let dut = shared(VerilatedWhoAmITop::new_unpowered());
        let bus = SimI2cBus::new();
        bus.attach(dut.clone());
        let mut i2c = bus.master(400_000);
        let nack = Err(ErrorKind::NoAcknowledge(NoAcknowledgeSource::Address));

        // no response without power
        assert_eq!(i2c.write(0x29, &[0x0F]), nack);

        // responds once powered
        dut.borrow_mut().set_vdd(true);
        let mut b = [0u8];
        i2c.write_read(0x29, &[0x0F], &mut b).unwrap();
        assert_eq!(b[0], 0xA5);
    }

    #[test]
    fn top_power_cycle_resets_registers() {
        let dut = shared(VerilatedWhoAmITop::new());
        let bus = SimI2cBus::new();
        bus.attach(dut.clone());
        let mut i2c = bus.master(400_000);
        i2c.write(0x29, &[0x10, 0x5C]).unwrap();
        let mut b = [0u8];
        i2c.write_read(0x29, &[0x10], &mut b).unwrap();
        assert_eq!(b[0], 0x5C);

        // power cycle
        dut.borrow_mut().set_vdd(false);
        bus.run_ns(1_000);
        dut.borrow_mut().set_vdd(true);
        bus.run_ns(1_000);

        i2c.write_read(0x29, &[0x10], &mut b).unwrap();
        assert_eq!(b[0], 0x00, "SCRATCH did not return to its reset value");
        i2c.write_read(0x29, &[0x0F], &mut b).unwrap();
        assert_eq!(b[0], 0xA5);
    }
}
