//! Adapter that presents `rtl/i2c_whoami.v` (generated by Verilator) as an [`I2cPinModel`].
//!
//! The smallest form of an adapter: the RTL has no system clock and runs on SCL / SDA only,
//! so it is evaluated whenever a line changes, and returns no `period_ps`.

use crate::bindings::i2c_whoami;
use virtual_bus::bus::i2c::sim::I2cPinModel;

/// I2C WHO_AM_I slave (address 0x29, 0x0F = 0xA5, 0x10 = SCRATCH)
pub struct VerilatedWhoAmI {
    m: i2c_whoami::Model,
}

impl VerilatedWhoAmI {
    pub const ADDRESS: u8 = 0x29;
    pub const WHO_AM_I: u8 = 0xA5;

    /// Creates the model and resets it.
    ///
    /// Verilator initializes ports to 0, so `rst_n` is set to 1 and then to 0
    /// to create the falling edge of the asynchronous reset (1 → 0 → 1)
    pub fn new() -> Self {
        let mut m = i2c_whoami::Model::new();
        m.set_scl(true);
        m.set_sda_i(true);
        for level in [true, false, true] {
            m.set_rst_n(level);
            m.eval();
        }
        Self { m }
    }
}

impl Default for VerilatedWhoAmI {
    fn default() -> Self {
        Self::new()
    }
}

impl I2cPinModel for VerilatedWhoAmI {
    fn set_inputs(&mut self, scl: bool, sda: bool) {
        self.m.set_scl(scl);
        self.m.set_sda_i(sda);
        self.m.eval();
    }

    fn sda_low(&self) -> bool {
        self.m.sda_low()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use embedded_hal::i2c::{ErrorKind, I2c, NoAcknowledgeSource};
    use virtual_bus::VirtualI2cBus;
    use virtual_bus::bus::i2c::sim::{PinLevelI2cSlave, SimI2cBus};
    use virtual_bus::devices::register::{I2cFormat, RegisterMap};

    /// A Rust model to put on the same bus as the RTL (0x00..=0x01 are read-write registers)
    fn rust_regs() -> RegisterMap {
        RegisterMap::new().rw(0x00, 0).rw(0x01, 0)
    }

    #[test]
    fn reads_who_am_i() {
        let bus = SimI2cBus::new();
        bus.attach(VerilatedWhoAmI::new());
        let mut i2c = bus.master(400_000);
        let mut b = [0u8; 2];
        i2c.write_read(0x29, &[0x0F], &mut b).unwrap();
        assert_eq!(b, [0xA5, 0x00]);
    }

    #[test]
    fn scratch_round_trip_and_wrong_address() {
        let bus = SimI2cBus::new();
        bus.attach(VerilatedWhoAmI::new());
        let mut i2c = bus.master(100_000);
        i2c.write(0x29, &[0x10, 0x3C]).unwrap();
        let mut b = [0u8];
        i2c.write_read(0x29, &[0x10], &mut b).unwrap();
        assert_eq!(b[0], 0x3C);
        assert_eq!(
            i2c.write(0x2A, &[0]),
            Err(ErrorKind::NoAcknowledge(NoAcknowledgeSource::Address))
        );
        // the bus is released after the failure
        assert!(bus.scl() && bus.sda());
    }

    /// The RTL and a Rust model on the same signal lines
    #[test]
    fn shares_wires_with_rust_pin_model() {
        let m = rust_regs();
        let bus = SimI2cBus::new();
        bus.attach(VerilatedWhoAmI::new());
        bus.attach(PinLevelI2cSlave::new(0x20, m.i2c(I2cFormat::new())));
        let mut i2c = bus.master(400_000);
        i2c.write(0x20, &[0x00, 0x81, 0x7E]).unwrap();
        let mut b = [0u8];
        i2c.write_read(0x29, &[0x0F], &mut b).unwrap();
        assert_eq!(b[0], 0xA5);
        let mut b = [0u8; 2];
        i2c.write_read(0x20, &[0x00], &mut b).unwrap();
        assert_eq!(b, [0x81, 0x7E]);
        assert_eq!(m.get(0x01), 0x7E);
    }

    /// The RTL at pin level and a Rust model at transaction level behind one `VirtualI2cBus`
    #[test]
    fn mixed_virtual_bus() {
        let lines = SimI2cBus::new();
        lines.attach(VerilatedWhoAmI::new());
        let m = rust_regs();
        let mut bus = VirtualI2cBus::new();
        bus.attach(0x20, m.i2c(I2cFormat::new())).unwrap();
        bus.attach_i2c(0x29, lines.master(400_000)).unwrap();

        let mut who = [0u8];
        bus.write_read(0x29, &[0x0F], &mut who).unwrap();
        bus.write(0x20, &[0x01, who[0]]).unwrap();
        assert_eq!(m.get(0x01), 0xA5);
        // accessing the Rust model does not advance the time of the signal lines
        let t = lines.now_ns();
        bus.write(0x20, &[0x01, 0]).unwrap();
        assert_eq!(lines.now_ns(), t);
    }
}
