//! virtual-bus demo: model your own Verilog with Verilator and drive it with embedded-hal drivers.
//!
//! - `build.rs` calls `virtual-bus-build` to model the RTL in `../verilog/rtl`
//! - [`bindings`] holds the generated bindings: a `Model` per RTL with a method per port
//! - each module is an adapter that attaches a generated model to virtual-bus's signal lines
//!
//! | Module | RTL | What it shows |
//! |---|---|---|
//! | [`i2c_whoami`] | `i2c_whoami.v` / `i2c_whoami_top.v` / `i2c_whoami_scl.v` | An I2C slave synchronized to a system clock, and one running on SCL / SDA only. Sharing a bus with Rust models. A chip top without output enables, with power-on reset |
//! | [`spi_whoami`] | `spi_whoami.v` / `spi_whoami_top.v` | An SPI slave clocked directly by SCK. A chip top without output enables, with power-on reset |
//! | [`spi_whoami_pin`] | (hand port) | A pin-level model ported from the RTL to Rust by hand, checked against the RTL |
//! | [`spi_counter`] | `spi_counter.v` | An SPI chip on a system clock: SCK / CS_N / MOSI are sampled with it, a counter keeps running between transfers, and an `irq` output outside the SPI pins |

/// Bindings generated by `virtual-bus-build`
pub mod bindings {
    include!(concat!(env!("OUT_DIR"), "/verilated_models.rs"));
}

pub mod i2c_whoami;
pub mod spi_counter;
pub mod spi_whoami;
pub mod spi_whoami_pin;
