//! virtual-bus demo: model your own Verilog with Verilator and drive it with embedded-hal drivers.
//!
//! - `build.rs` calls `virtual-bus-build` to model the RTL in `../verilog/rtl`
//! - [`bindings`] holds the generated bindings: a `Model` per RTL with a method per port
//! - each module is an adapter that attaches a generated model to virtual-bus's signal lines
//! - `examples/spi_counter.rs` drives one from start to end
//!   (`cargo run -p rtl-demo --example spi_counter`)
//!
//! | Module | RTL | What it shows |
//! |---|---|---|
//! | [`i2c_whoami`] | `i2c_whoami.v`, `i2c_whoami_top.v` | The smallest adapter: an I2C slave without a system clock, evaluated whenever a line changes. Sharing a bus with Rust models. The same slave as a chip top with an `inout` pad and a power-on reset |
//! | [`spi_counter`] | `spi_counter.v` | An SPI chip on a system clock: evaluated on `tick`, a counter that keeps running between transfers, an `irq` output outside the SPI pins, and VCD waveforms |

/// Bindings generated by `virtual-bus-build`
pub mod bindings {
    include!(concat!(env!("OUT_DIR"), "/verilated_models.rs"));
}

pub mod i2c_whoami;
pub mod spi_counter;
