//! Adapter that presents `rtl/spi_counter.v` (generated by Verilator) as an [`SpiPinModel`].
//!
//! Unlike `spi_whoami.v`, this chip runs on a 50 MHz system clock and samples SCK / CS_N / MOSI
//! with it (two flip-flops), so it is evaluated on [`SpiPinModel::tick`]. Its counter keeps running
//! between transfers, and it has an output outside the SPI pins (`irq`), read with
//! [`SpiCounter::irq`].

use std::io;
use std::path::Path;

use crate::bindings::spi_counter;
use virtual_bus::bus::spi::sim::SpiPinModel;

/// SPI timer / counter (mode 0).
///
/// First byte: bit7 = read, bits 6..0 = address; the address auto-increments after that.
/// See the `REG_*` constants for the registers
pub struct SpiCounter {
    m: spi_counter::Model,
}

impl SpiCounter {
    pub const ID: u8 = 0x5C;
    /// 50 MHz system clock
    pub const PERIOD_PS: u64 = 20_000;

    /// ID (RO)
    pub const REG_ID: u8 = 0x00;
    /// bit0 EN, bit1 CLR (write 1 to clear COUNT, reads 0), bit2 IRQ_EN
    pub const REG_CTRL: u8 = 0x01;
    /// COUNT increments every PRESCALE + 1 system clock cycles
    pub const REG_PRESCALE: u8 = 0x02;
    /// 8-bit counter (RO)
    pub const REG_COUNT: u8 = 0x03;
    /// STATUS.MATCH is set when COUNT reaches this value (reset value 0xFF)
    pub const REG_COMPARE: u8 = 0x04;
    /// bit0 MATCH (write 1 to clear)
    pub const REG_STATUS: u8 = 0x05;

    pub const CTRL_EN: u8 = 0x01;
    pub const CTRL_CLR: u8 = 0x02;
    pub const CTRL_IRQ_EN: u8 = 0x04;

    /// Creates the model and resets it.
    ///
    /// Verilator initializes ports to 0, so `rst_n` is set to 1 and then to 0 to create
    /// the falling edge of the asynchronous reset
    pub fn new() -> Self {
        Self::reset(spi_counter::Model::new())
    }

    /// Like [`Self::new`], and writes a VCD of every signal in the RTL to `path`,
    /// at the bus's simulated time. The VCD is closed when the model is dropped
    pub fn with_vcd(path: impl AsRef<Path>) -> io::Result<Self> {
        let mut m = spi_counter::Model::new();
        m.open_vcd(path)?;
        Ok(Self::reset(m))
    }

    fn reset(mut m: spi_counter::Model) -> Self {
        m.set_cs_n(true);
        for level in [true, false, true] {
            m.set_rst_n(level);
            m.eval();
        }
        Self { m }
    }

    fn clock(&mut self) {
        self.m.set_clk(false);
        // in the VCD, the low half goes half a period before this rising edge
        self.m.eval_before(Self::PERIOD_PS / 2);
        self.m.set_clk(true);
        self.m.eval();
    }

    /// The interrupt output (MATCH && IRQ_EN)
    pub fn irq(&self) -> bool {
        self.m.irq()
    }
}

impl Default for SpiCounter {
    fn default() -> Self {
        Self::new()
    }
}

impl SpiPinModel for SpiCounter {
    fn set_inputs(&mut self, cs_n: bool, sck: bool, mosi: bool) {
        // a synchronous circuit: evaluating on the system clock is enough.
        // When writing a VCD, evaluate now too so the inputs show up when they change
        self.m.set_cs_n(cs_n);
        self.m.set_sck(sck);
        self.m.set_mosi(mosi);
        if self.m.is_tracing() {
            self.m.eval();
        }
    }

    fn miso(&self) -> Option<bool> {
        self.m.miso_oe().then(|| self.m.miso())
    }

    fn period_ps(&self) -> Option<u64> {
        Some(Self::PERIOD_PS)
    }

    fn tick(&mut self) {
        self.clock();
    }

    fn set_time_ps(&mut self, now_ps: u64) {
        self.m.set_time_ps(now_ps);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use embedded_hal::delay::DelayNs;
    use embedded_hal::spi::{MODE_0, SpiDevice};
    use embedded_hal_bus::spi::ExclusiveDevice;
    use virtual_bus::bus::SimDelay;
    use virtual_bus::bus::spi::sim::{SimCsPin, SimSpiBus, SimSpiMaster};
    use virtual_bus::{Shared, shared};

    /// The whole flow at a glance: set COMPARE, start the counter with its interrupt,
    /// wait a little, and `irq` rises. The tests after this one check each part in detail
    #[test]
    fn irq_rises_when_count_reaches_compare() {
        let bus = SimSpiBus::new();
        let mut delay = bus.delay();
        // keep a handle to the model to read `irq`, which is not an SPI pin
        let dut = shared(SpiCounter::new());
        let cs = bus.add_device(dut.clone());
        // at most about clk / 8 (6 MHz): the chip samples SCK with its 50 MHz clock
        let spi = bus.master(MODE_0, 1_000_000).unwrap();
        let mut dev = ExclusiveDevice::new(spi, cs, bus.delay()).unwrap();

        assert!(!dut.borrow().irq());
        dev.write(&[0x04, 0x0F]).unwrap(); // COMPARE = 15
        dev.write(&[0x01, 0x05]).unwrap(); // CTRL = EN | IRQ_EN
        // PRESCALE is 0: COUNT goes up every 20 ns and reaches 15 well within 1 µs
        delay.delay_us(1);
        assert!(dut.borrow().irq());
    }

    type Dev = ExclusiveDevice<SimSpiMaster, SimCsPin, SimDelay>;

    /// A 1 MHz mode 0 device, with the model kept outside the bus to read `irq`
    fn setup() -> (SimSpiBus, Dev, Shared<SpiCounter>) {
        let dut = shared(SpiCounter::new());
        let bus = SimSpiBus::new();
        let cs = bus.add_device(dut.clone());
        let spi = bus.master(MODE_0, 1_000_000).unwrap();
        let dev = ExclusiveDevice::new(spi, cs, bus.delay()).unwrap();
        (bus, dev, dut)
    }

    fn read(dev: &mut Dev, reg: u8) -> u8 {
        let mut b = [0x80 | reg, 0];
        dev.transfer_in_place(&mut b).unwrap();
        b[1]
    }

    fn write(dev: &mut Dev, reg: u8, value: u8) {
        dev.write(&[reg, value]).unwrap();
    }

    #[test]
    fn reads_id() {
        let (_bus, mut dev, _dut) = setup();
        assert_eq!(read(&mut dev, SpiCounter::REG_ID), SpiCounter::ID);
    }

    #[test]
    fn writes_and_reads_back_with_auto_increment() {
        let (_bus, mut dev, _dut) = setup();
        // PRESCALE, COUNT (read-only, ignored), COMPARE in one frame
        dev.write(&[SpiCounter::REG_PRESCALE, 49, 0x12, 0x80])
            .unwrap();
        // read right after the write: the frames must not run together
        let mut b = [0x80 | SpiCounter::REG_ID, 0, 0, 0, 0, 0, 0];
        dev.transfer_in_place(&mut b).unwrap();
        // ID, CTRL, PRESCALE, COUNT, COMPARE, STATUS
        assert_eq!(&b[1..], [0x5C, 0x00, 49, 0x00, 0x80, 0x00]);
    }

    #[test]
    fn counter_runs_between_transfers_and_clears() {
        let (bus, mut dev, _dut) = setup();
        write(&mut dev, SpiCounter::REG_PRESCALE, 49); // +1 every 1 µs
        write(&mut dev, SpiCounter::REG_CTRL, SpiCounter::CTRL_EN);
        bus.run_ns(50_000);
        write(&mut dev, SpiCounter::REG_CTRL, 0);

        // 50 µs of waiting, plus the time on the bus: the EN frame after its last rising SCK edge
        // (0.5 µs) and the stopping frame up to its last rising SCK edge (15.5 µs). 66 counts
        let count = read(&mut dev, SpiCounter::REG_COUNT);
        assert!((64..=68).contains(&count), "{count}");
        // stopped: the value holds
        bus.run_ns(20_000);
        assert_eq!(read(&mut dev, SpiCounter::REG_COUNT), count);

        // CLR clears COUNT and is not stored
        write(&mut dev, SpiCounter::REG_CTRL, SpiCounter::CTRL_CLR);
        assert_eq!(read(&mut dev, SpiCounter::REG_COUNT), 0);
        assert_eq!(read(&mut dev, SpiCounter::REG_CTRL), 0);
    }

    #[test]
    fn match_raises_irq_only_with_irq_en() {
        let (_bus, mut dev, dut) = setup();
        write(&mut dev, SpiCounter::REG_COMPARE, 5);
        // PRESCALE = 0: COUNT reaches 5 within 6 system clock cycles
        write(&mut dev, SpiCounter::REG_CTRL, SpiCounter::CTRL_EN);
        assert_eq!(read(&mut dev, SpiCounter::REG_STATUS), 0x01);
        assert!(!dut.borrow().irq(), "irq without IRQ_EN");

        // stop the counter and enable the interrupt
        write(&mut dev, SpiCounter::REG_CTRL, SpiCounter::CTRL_IRQ_EN);
        assert!(dut.borrow().irq());

        // writing 1 to STATUS clears MATCH, and with it irq
        write(&mut dev, SpiCounter::REG_STATUS, 0x01);
        assert!(!dut.borrow().irq());
        assert_eq!(read(&mut dev, SpiCounter::REG_STATUS), 0x00);
    }

    #[test]
    fn miso_is_high_impedance_while_deselected() {
        let (bus, _dev, _dut) = setup();
        bus.run_ns(1_000);
        assert!(bus.miso()); // pull-up
        assert_eq!(bus.contentions(), 0);
    }
}
