//! Adapters that present `rtl/spi_whoami.v` (generated by Verilator) as an [`SpiPinModel`].
//! The RTL is clocked directly by SCK, so it is evaluated whenever a pin changes.
//!
//! - [`VerilatedSpiWhoAmI`]: uses the core (separate `miso` / `miso_oe` ports) as is
//! - [`VerilatedSpiWhoAmITop`]: the chip top without output enable (`spi_whoami_top.v`, tri-state MISO),
//!   wrapped in a simulation wrapper (`sim/spi_whoami_sim.v`)

use crate::bindings::{spi_whoami, spi_whoami_sim};
use virtual_bus::bus::spi::sim::SpiPinModel;

/// SPI WHO_AM_I slave (0x0F = 0x33, 0x20 = CTRL, modes 0 / 3)
pub struct VerilatedSpiWhoAmI {
    m: spi_whoami::Model,
}

impl VerilatedSpiWhoAmI {
    pub const WHO_AM_I: u8 = 0x33;

    /// Creates the model and pulses RST_N (with CS_N high).
    ///
    /// Verilator initializes ports to 0, so `rst_n` is set to 1 and then to 0
    /// to create the falling edge of the asynchronous reset
    pub fn new() -> Self {
        let mut m = spi_whoami::Model::new();
        m.set_cs_n(true);
        for level in [true, false, true] {
            m.set_rst_n(level);
            m.eval();
        }
        Self { m }
    }
}

impl Default for VerilatedSpiWhoAmI {
    fn default() -> Self {
        Self::new()
    }
}

impl SpiPinModel for VerilatedSpiWhoAmI {
    fn set_inputs(&mut self, cs_n: bool, sck: bool, mosi: bool) {
        self.m.set_cs_n(cs_n);
        self.m.set_sck(sck);
        self.m.set_mosi(mosi);
        self.m.eval();
    }

    fn miso(&self) -> Option<bool> {
        self.m.miso_oe().then(|| self.m.miso())
    }
}

/// SPI WHO_AM_I slave as a chip top without output enable.
///
/// MISO is resolved (pulled up when undriven) inside the Verilog wrapper; the Rust side only sees
/// the resolved level. Whether the DUT drives 1 or is Hi-Z cannot be told apart, so
/// [`SpiPinModel::miso`] returns `Some(false)` only when low, and `None` (undriven) when high.
/// Values get through correctly, but MISO contention while the DUT drives 1 is not counted in
/// [`virtual_bus::bus::spi::sim::SimSpiBus::contentions`].
///
/// There is no reset pin; the Verilog creates a power-on reset from vdd. This chip has no
/// system clock, so the POR has no delay: while the power ([`Self::set_vdd`]) is off it is held in
/// reset (MISO is Hi-Z), and the moment power comes back all registers, CTRL included, return to their reset values
pub struct VerilatedSpiWhoAmITop {
    m: spi_whoami_sim::Model,
}

impl VerilatedSpiWhoAmITop {
    pub const WHO_AM_I: u8 = VerilatedSpiWhoAmI::WHO_AM_I;

    /// Creates the model with power on (CS_N high)
    pub fn new() -> Self {
        let mut s = Self::new_unpowered();
        s.set_vdd(true);
        s
    }

    /// Creates the model with power off
    pub fn new_unpowered() -> Self {
        let mut m = spi_whoami_sim::Model::new();
        m.set_cs_n(true);
        // move vdd 1 → 0 so the power-off reset surely happens (staying at the initial 0 gives no edge)
        for level in [true, false] {
            m.set_vdd(level);
            m.eval();
        }
        Self { m }
    }

    /// Turns the power (vdd) on / off. gnd is tied to 0 inside the wrapper
    pub fn set_vdd(&mut self, on: bool) {
        self.m.set_vdd(on);
        self.m.eval();
    }

    /// The MISO level resolved inside the wrapper
    pub fn miso_level(&self) -> bool {
        self.m.miso_level()
    }
}

impl Default for VerilatedSpiWhoAmITop {
    fn default() -> Self {
        Self::new()
    }
}

impl SpiPinModel for VerilatedSpiWhoAmITop {
    fn set_inputs(&mut self, cs_n: bool, sck: bool, mosi: bool) {
        self.m.set_cs_n(cs_n);
        self.m.set_sck(sck);
        self.m.set_mosi(mosi);
        self.m.eval();
    }

    fn miso(&self) -> Option<bool> {
        (!self.miso_level()).then_some(false)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use embedded_hal::spi::{MODE_0, MODE_1, MODE_2, MODE_3, Mode, SpiDevice};
    use embedded_hal_bus::spi::ExclusiveDevice;
    use virtual_bus::bus::spi::sim::SimSpiBus;

    fn who_am_i(dut: impl SpiPinModel + 'static, mode: Mode) -> u8 {
        let bus = SimSpiBus::new();
        let cs = bus.add_device(dut);
        let spi = bus.master(mode, 2_000_000).unwrap();
        let mut dev = ExclusiveDevice::new(spi, cs, bus.delay()).unwrap();
        let mut b = [0x8F, 0];
        dev.transfer_in_place(&mut b).unwrap();
        b[1]
    }

    #[test]
    fn mode_0_and_3_work() {
        for mode in [MODE_0, MODE_3] {
            assert_eq!(who_am_i(VerilatedSpiWhoAmI::new(), mode), 0x33);
            assert_eq!(who_am_i(VerilatedSpiWhoAmITop::new(), mode), 0x33);
        }
    }

    #[test]
    fn mode_1_and_2_garble_who_am_i_identically() {
        for mode in [MODE_1, MODE_2] {
            let core = who_am_i(VerilatedSpiWhoAmI::new(), mode);
            assert_ne!(core, 0x33);
            assert_eq!(who_am_i(VerilatedSpiWhoAmITop::new(), mode), core);
        }
    }

    #[test]
    fn miso_is_high_impedance_while_deselected() {
        let bus = SimSpiBus::new();
        let _a = bus.add_device(VerilatedSpiWhoAmI::new());
        let _b = bus.add_device(VerilatedSpiWhoAmITop::new());
        assert!(bus.miso()); // pull-up
        assert_eq!(bus.contentions(), 0);
    }

    /// Applies the same pin operations to the core and the top one edge at a time, and compares MISO.
    /// The top should match the core except that it cannot tell 1 from Hi-Z
    #[test]
    fn top_matches_core_edge_by_edge() {
        let mut core = VerilatedSpiWhoAmI::new();
        let mut top = VerilatedSpiWhoAmITop::new();
        let mut steps = 0;
        let mut drive = |cs_n: bool, sck: bool, mosi: bool| {
            core.set_inputs(cs_n, sck, mosi);
            top.set_inputs(cs_n, sck, mosi);
            let expected = match core.miso() {
                None | Some(true) => None,
                Some(false) => Some(false),
            };
            assert_eq!(top.miso(), expected, "step {steps}");
            assert_eq!(
                top.miso_level(),
                core.miso().unwrap_or(true),
                "step {steps}"
            );
            steps += 1;
        };
        // mode 0 frames assembled by hand
        let frames: [&[u8]; 4] = [
            &[0x20, 0xFF],       // CTRL = 0xFF (MISO stays at 1 for a while)
            &[0xA0, 0x00],       // read CTRL
            &[0xCF, 0x00, 0x00], // 2 bytes from WHO_AM_I with MS
            &[0x20, 0x5A],
        ];
        for frame in frames {
            drive(true, false, false);
            drive(false, false, false);
            for &byte in frame {
                for i in (0..8).rev() {
                    let bit = byte & (1 << i) != 0;
                    drive(false, false, bit);
                    drive(false, true, bit);
                    drive(false, false, bit);
                }
            }
            drive(true, false, false);
        }
        assert!(steps > 100);
    }

    // ---- power-on reset (chip top) ----

    #[test]
    fn top_unpowered_is_silent_and_power_cycle_resets_ctrl() {
        use virtual_bus::shared;
        let dut = shared(VerilatedSpiWhoAmITop::new_unpowered());
        let bus = SimSpiBus::new();
        let cs = bus.add_device(dut.clone());
        let spi = bus.master(MODE_0, 2_000_000).unwrap();
        let mut dev = ExclusiveDevice::new(spi, cs, bus.delay()).unwrap();
        let read = |dev: &mut ExclusiveDevice<_, _, _>, cmd: u8| {
            let mut b = [cmd, 0];
            dev.transfer_in_place(&mut b).unwrap();
            b[1]
        };

        // without power, MISO is Hi-Z (0xFF thanks to the pull-up)
        assert_eq!(read(&mut dev, 0x8F), 0xFF);

        dut.borrow_mut().set_vdd(true);
        assert_eq!(read(&mut dev, 0x8F), 0x33);
        dev.write(&[0x20, 0xA6]).unwrap();
        assert_eq!(read(&mut dev, 0xA0), 0xA6);

        // a power cycle brings CTRL back to its reset value 0
        dut.borrow_mut().set_vdd(false);
        bus.run_ns(1_000);
        dut.borrow_mut().set_vdd(true);
        assert_eq!(read(&mut dev, 0xA0), 0x00);
        assert_eq!(read(&mut dev, 0x8F), 0x33);
    }
}
