//! Runtime support for models generated with Verilator.
//!
//! The build side is handled by the `virtual-bus-build` crate. When the user's `build.rs` lists the RTL,
//! it generates a C ABI glue layer (new / free / eval / set / get) and one Rust module per model.
//! Each module has a typed `Model` (a method per port) built on [`RawModel`], plus `VTABLE` and
//! pin-number constants for using [`RawModel`] directly.
//!
//! ```ignore
//! mod bindings {
//!     include!(concat!(env!("OUT_DIR"), "/verilated_models.rs"));
//! }
//! use bindings::spi_whoami;
//!
//! // usually: the typed model
//! let mut m = spi_whoami::Model::new();
//! m.set_cs_n(true);
//! m.eval();
//! let oe = m.miso_oe();
//!
//! // or by pin number
//! let mut raw = virtual_bus::verilated::RawModel::new(&spi_whoami::VTABLE);
//! raw.set(spi_whoami::CS_N, 1);
//! raw.eval();
//! let oe = raw.get_bit(spi_whoami::MISO_OE);
//! ```
//!
//! # Waveforms
//!
//! A model built with `.trace()` in `build.rs` can write a VCD of all its signals with
//! [`RawModel::open_vcd`]. The VCD follows the bus's simulated time: an adapter forwards the bus's
//! `set_time_ps` to [`RawModel::set_time_ps`], and the values a model settles to at each moment
//! are written when the time moves on (the bus may evaluate a model several times at one moment).
//! Every model has its own Verilator context, so any number of models can trace at once,
//! in parallel tests too.

use core::ffi::{c_char, c_void};
use core::ptr::NonNull;
use std::ffi::CString;
use std::io;
use std::path::Path;

/// Function table of the generated glue. Generated by `virtual-bus-build`
pub struct VTable {
    pub name: &'static str,
    pub new: unsafe extern "C" fn() -> *mut c_void,
    pub free: unsafe extern "C" fn(*mut c_void),
    pub eval: unsafe extern "C" fn(*mut c_void),
    pub set: unsafe extern "C" fn(*mut c_void, u32, u64),
    pub get: unsafe extern "C" fn(*mut c_void, u32) -> u64,
    /// Present when the model was built with tracing
    pub trace: Option<TraceVTable>,
}

/// Waveform functions of a model built with tracing. Generated by `virtual-bus-build`
pub struct TraceVTable {
    /// Opens a VCD at the path. Returns false if it could not be opened
    pub open: unsafe extern "C" fn(*mut c_void, *const c_char) -> bool,
    /// Writes the current values at a time (ps)
    pub dump: unsafe extern "C" fn(*mut c_void, u64),
    /// Flushes and closes the VCD
    pub close: unsafe extern "C" fn(*mut c_void),
}

/// The state of an open VCD
struct Wave {
    /// The bus's current time (ps)
    now: u64,
    /// Evaluated at `now` and not yet written
    dirty: bool,
    /// The time of the last write; Verilator ignores writes that do not move forward
    last: Option<u64>,
}

/// One instance of a Verilator model. Each instance has its own VerilatedContext
pub struct RawModel {
    ptr: NonNull<c_void>,
    vt: &'static VTable,
    wave: Option<Wave>,
}

impl RawModel {
    pub fn new(vt: &'static VTable) -> Self {
        // SAFETY: the glue's new just allocates an Inst and returns it
        let p = unsafe { (vt.new)() };
        Self {
            ptr: NonNull::new(p).expect("failed to create the Verilator model"),
            vt,
            wave: None,
        }
    }

    pub fn name(&self) -> &'static str {
        self.vt.name
    }

    /// Puts a value on an input port (evaluate with [`Self::eval`])
    pub fn set(&mut self, pin: u32, value: u64) {
        // SAFETY: ptr is a live instance obtained from new
        unsafe { (self.vt.set)(self.ptr.as_ptr(), pin, value) }
    }

    pub fn get(&self, pin: u32) -> u64 {
        // SAFETY: as above. get only reads
        unsafe { (self.vt.get)(self.ptr.as_ptr(), pin) }
    }

    pub fn get_bit(&self, pin: u32) -> bool {
        self.get(pin) != 0
    }

    pub fn eval(&mut self) {
        // SAFETY: as above
        unsafe { (self.vt.eval)(self.ptr.as_ptr()) }
        if let Some(w) = &mut self.wave {
            w.dirty = true;
        }
    }

    /// Whether the model was built with tracing (`.trace()` in `build.rs`)
    pub fn can_trace(&self) -> bool {
        self.vt.trace.is_some()
    }

    /// Whether a VCD is open
    pub fn is_tracing(&self) -> bool {
        self.wave.is_some()
    }

    /// Starts writing a VCD of every signal in the model to `path`, beginning with the current values.
    ///
    /// Fails if the model was built without tracing, a VCD is already open, or the file cannot be created
    pub fn open_vcd(&mut self, path: impl AsRef<Path>) -> io::Result<()> {
        let path = path.as_ref();
        let Some(t) = &self.vt.trace else {
            return Err(io::Error::new(
                io::ErrorKind::Unsupported,
                format!(
                    "model {} was built without tracing; add .trace() to it in build.rs",
                    self.vt.name
                ),
            ));
        };
        if self.wave.is_some() {
            return Err(io::Error::new(
                io::ErrorKind::AlreadyExists,
                "a VCD is already open for this model",
            ));
        }
        let c_path = path
            .to_str()
            .and_then(|s| CString::new(s).ok())
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "unusable VCD path"))?;
        // SAFETY: ptr is live; the glue copies the path before returning
        let opened = unsafe { (t.open)(self.ptr.as_ptr(), c_path.as_ptr()) };
        if !opened {
            return Err(io::Error::other(format!(
                "could not open {}",
                path.display()
            )));
        }
        self.wave = Some(Wave {
            now: 0,
            dirty: true,
            last: None,
        });
        Ok(())
    }

    /// The bus's simulated time moved to `now_ps`. Forward `I2cPinModel::set_time_ps` /
    /// `SpiPinModel::set_time_ps` here. Does nothing unless a VCD is open
    pub fn set_time_ps(&mut self, now_ps: u64) {
        let Some(w) = &self.wave else { return };
        if now_ps != w.now {
            if w.dirty {
                let t = w.now;
                self.dump(t);
            }
            let w = self.wave.as_mut().unwrap();
            w.dirty = false;
            w.now = now_ps;
        }
    }

    /// Evaluates, and writes the result to the VCD `ps` before the current time.
    ///
    /// For a system clock: the bus calls `tick` only at the rising edge, so evaluate the low half
    /// with `eval_before(period_ps / 2)` and then the rising edge with [`Self::eval`].
    /// The write is skipped if something was already written at or after that time
    pub fn eval_before(&mut self, ps: u64) {
        // SAFETY: as in eval
        unsafe { (self.vt.eval)(self.ptr.as_ptr()) }
        if let Some(w) = &self.wave {
            let t = w.now.saturating_sub(ps);
            self.dump(t);
        }
    }

    /// Writes the last values and closes the VCD (also done when the model is dropped)
    pub fn close_vcd(&mut self) {
        let Some(w) = &self.wave else { return };
        if w.dirty {
            let t = w.now;
            self.dump(t);
        }
        if let Some(t) = &self.vt.trace {
            // SAFETY: ptr is live
            unsafe { (t.close)(self.ptr.as_ptr()) }
        }
        self.wave = None;
    }

    fn dump(&mut self, t: u64) {
        let (Some(trace), Some(w)) = (&self.vt.trace, &mut self.wave) else {
            return;
        };
        if w.last.is_some_and(|last| t <= last) {
            return;
        }
        // SAFETY: ptr is live and a VCD is open
        unsafe { (trace.dump)(self.ptr.as_ptr(), t) }
        w.last = Some(t);
    }
}

impl Drop for RawModel {
    fn drop(&mut self) {
        self.close_vcd();
        // SAFETY: frees the pointer obtained from new exactly once
        unsafe { (self.vt.free)(self.ptr.as_ptr()) }
    }
}
