//! Runtime support for models generated with Verilator.
//!
//! The build side is handled by the `virtual-bus-build` crate. When the user's `build.rs` lists the RTL and
//! ports, it generates a C ABI glue layer (new / free / eval / set / get) and one Rust module per model
//! (`VTABLE` and constants for the pin numbers).
//! This module runs them as a [`RawModel`].
//!
//! ```ignore
//! mod bindings {
//!     include!(concat!(env!("OUT_DIR"), "/verilated_models.rs"));
//! }
//! use bindings::spi_whoami as pins;
//!
//! let mut raw = virtual_bus::verilated::RawModel::new(&pins::VTABLE);
//! raw.set(pins::CS_N, 1);
//! raw.eval();
//! let oe = raw.get_bit(pins::MISO_OE);
//! ```

use core::ffi::c_void;
use core::ptr::NonNull;

/// Function table of the generated glue. Generated by `virtual-bus-build`
pub struct VTable {
    pub name: &'static str,
    pub new: unsafe extern "C" fn() -> *mut c_void,
    pub free: unsafe extern "C" fn(*mut c_void),
    pub eval: unsafe extern "C" fn(*mut c_void),
    pub set: unsafe extern "C" fn(*mut c_void, u32, u64),
    pub get: unsafe extern "C" fn(*mut c_void, u32) -> u64,
}

/// One instance of a Verilator model. Each instance has its own VerilatedContext
pub struct RawModel {
    ptr: NonNull<c_void>,
    vt: &'static VTable,
}

impl RawModel {
    pub fn new(vt: &'static VTable) -> Self {
        // SAFETY: the glue's new just allocates an Inst and returns it
        let p = unsafe { (vt.new)() };
        Self {
            ptr: NonNull::new(p).expect("failed to create the Verilator model"),
            vt,
        }
    }

    pub fn name(&self) -> &'static str {
        self.vt.name
    }

    /// Puts a value on an input port (evaluate with [`Self::eval`])
    pub fn set(&mut self, pin: u32, value: u64) {
        // SAFETY: ptr is a live instance obtained from new
        unsafe { (self.vt.set)(self.ptr.as_ptr(), pin, value) }
    }

    pub fn get(&self, pin: u32) -> u64 {
        // SAFETY: as above. get only reads
        unsafe { (self.vt.get)(self.ptr.as_ptr(), pin) }
    }

    pub fn get_bit(&self, pin: u32) -> bool {
        self.get(pin) != 0
    }

    pub fn eval(&mut self) {
        // SAFETY: as above
        unsafe { (self.vt.eval)(self.ptr.as_ptr()) }
    }
}

impl Drop for RawModel {
    fn drop(&mut self) {
        // SAFETY: frees the pointer obtained from new exactly once
        unsafe { (self.vt.free)(self.ptr.as_ptr()) }
    }
}
